# require_ci_to_pass: yes # require CI to pass before uploading coverage

comment:
  layout: "header, diff, components, files" # show component info in the PR comment
  behavior: default

component_management:
  default_rules: # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doesn't have a status defined will have a project type one
        target: auto
        branches:
          - "*" # all branches
      - type: patch
        target: auto
        branches:
          - "*" # all branches
