services:
  random-image-server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      # the config file is mounted to the container
      - ./config.toml:/etc/random-image-server/config.toml
      # you can mount your images wherever, just make sure it's where you point to in the config file
      - ./assets:/path/to/image/directory

